---
driver:
  name: localhost

provisioner:
  name: chef_zero

platforms:
  - name: macosx

suites:
  - name: default
    run_list:
      - recipe[my-dev-machine]
    attributes:
      mac_app_store:
        username: <%= ENV['APPLE_ID_USERNAME'] %>
        password: <%= ENV['APPLE_ID_PASSWORD'] %>
